import crypto from "crypto";

export function parsePRUrl(url) {
  const match = url.match(/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/);
  if (!match) throw new Error("Invalid GitHub PR URL");
  return { owner: match[1], repo: match[2], number: match[3] };
}

export function verifySlackSignature(headers, rawBody, secret) {
  if (!secret) return false;
  const timestamp = headers["x-slack-request-timestamp"];
  const slackSig = headers["x-slack-signature"];
  if (!timestamp || !slackSig) return false;

  // Reject requests older than 5 minutes (replay attack protection)
  if (Math.abs(Date.now() / 1000 - Number(timestamp)) > 300) return false;

  const sigBase = `v0:${timestamp}:${rawBody}`;
  const computed =
    "v0=" + crypto.createHmac("sha256", secret).update(sigBase).digest("hex");

  if (computed.length !== slackSig.length) return false;
  return crypto.timingSafeEqual(Buffer.from(computed), Buffer.from(slackSig));
}

export function fmtDate(iso) {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export function splitIntoBlocks(text, limit = 2900) {
  const blocks = [];
  const lines = text.split("\n");
  let chunk = "";

  for (const line of lines) {
    const candidate = chunk ? `${chunk}\n${line}` : line;
    if (candidate.length > limit) {
      if (chunk) blocks.push(chunk);
      // A single line longer than limit must be hard-split
      if (line.length > limit) {
        for (let i = 0; i < line.length; i += limit) {
          blocks.push(line.slice(i, i + limit));
        }
        chunk = "";
      } else {
        chunk = line;
      }
    } else {
      chunk = candidate;
    }
  }
  if (chunk) blocks.push(chunk);

  return blocks.map((t) => ({ type: "section", text: { type: "mrkdwn", text: t } }));
}

export function formatCI(runs) {
  if (!runs.length) return "_No CI checks found_";

  const counts = { success: 0, failure: 0, pending: 0, skipped: 0 };
  const failed = [];

  for (const run of runs) {
    const c = run.conclusion;
    if (c === "success") counts.success++;
    else if (c === "failure" || c === "timed_out") {
      counts.failure++;
      failed.push(run.name);
    } else if (c === "skipped" || c === "neutral") counts.skipped++;
    else counts.pending++; // null = in_progress
  }

  let out = `✅ ${counts.success} passed  ❌ ${counts.failure} failed  ⏳ ${counts.pending} pending  ⏭ ${counts.skipped} skipped`;
  if (failed.length) out += `\n*Failed checks:* ${failed.join(", ")}`;
  return out;
}

export function formatReviewers(pr) {
  const requested = (pr.requested_reviewers || []).map(
    (r) => `${r.login} _(requested)_`
  );
  if (!requested.length) return null;
  return requested.join("  ·  ");
}

export function buildSlackBlocks(pr, checkRuns, summaryBlocks) {
  const status = pr.merged_at
    ? "✅ Merged"
    : pr.state === "closed"
    ? "🔴 Closed"
    : pr.draft
    ? "🚧 Draft"
    : "🟢 Open";

  const ci = formatCI(checkRuns);
  const reviewSummary = formatReviewers(pr);

  return [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `PR #${pr.number}: ${pr.title.slice(0, 140)}`,
        emoji: true,
      },
    },
    {
      type: "section",
      fields: [
        { type: "mrkdwn", text: `*Status*\n${status}` },
        { type: "mrkdwn", text: `*Author*\n${pr.user.login}` },
        { type: "mrkdwn", text: `*Created*\n${fmtDate(pr.created_at)}` },
        { type: "mrkdwn", text: `*Last Updated*\n${fmtDate(pr.updated_at)}` },
        {
          type: "mrkdwn",
          text: `*Merged*\n${pr.merged_at ? fmtDate(pr.merged_at) : "—"}`,
        },
        {
          type: "mrkdwn",
          text: `*Diff*\n+${pr.additions} / -${pr.deletions} across ${pr.changed_files} file${pr.changed_files !== 1 ? "s" : ""}`,
        },
      ],
    },
    ...(reviewSummary
      ? [
          {
            type: "section",
            text: { type: "mrkdwn", text: `*Reviewers*\n${reviewSummary}` },
          },
        ]
      : []),
    { type: "divider" },
    {
      type: "section",
      text: { type: "mrkdwn", text: `*CI Status*\n${ci}` },
    },
    { type: "divider" },
    ...summaryBlocks.flatMap(({ title, text }) =>
      splitIntoBlocks(title ? `*${title}*\n${text}` : text)
    ),
    {
      type: "actions",
      elements: [
        {
          type: "button",
          text: { type: "plain_text", text: "Open PR →", emoji: true },
          url: pr.html_url,
          style: "primary",
        },
      ],
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `_Summary generated by gh-summary bot · ${new Date().toUTCString()}_`,
        },
      ],
    },
  ];
}
