/**
 * Block Kit Summary Builders
 * Handles AI summary parsing and text splitting into Slack blocks
 */
import { buildHeaderBlock, buildMetadataBlock, buildReviewersBlock, buildDividerBlock, buildCIBlock, formatCI, formatReviewers } from "./metadata.js";

const BLOCK_LIMIT = 2900;

/**
 * Split long text into multiple Slack section blocks
 */
export function splitIntoBlocks(text, limit = BLOCK_LIMIT) {
  const blocks = [];
  const lines = text.split("\n");
  let chunk = "";

  for (const line of lines) {
    const candidate = chunk ? `${chunk}\n${line}` : line;
    
    if (candidate.length > limit) {
      if (chunk) blocks.push(chunk);
      
      // A single line longer than limit must be hard-split
      if (line.length > limit) {
        for (let i = 0; i < line.length; i += limit) {
          blocks.push(line.slice(i, i + limit));
        }
        chunk = "";
      } else {
        chunk = line;
      }
    } else {
      chunk = candidate;
    }
  }
  
  if (chunk) blocks.push(chunk);

  return blocks.map((t) => ({ 
    type: "section", 
    text: { type: "mrkdwn", text: t } 
  }));
}

/**
 * Build AI summary blocks from parsed sections
 */
export function buildSummaryBlocks(summarySections) {
  return summarySections.flatMap(({ title, text }) =>
    splitIntoBlocks(title ? `*${title}*\n${text}` : text)
  );
}

/**
 * Build complete Slack message with all blocks
 */
export function buildSlackBlocks(pr, checkRuns, summarySections) {
  const status = pr.merged_at
    ? "✅ Merged"
    : pr.state === "closed"
    ? "🔴 Closed"
    : pr.draft
    ? "🚧 Draft"
    : "🟢 Open";

  const ci = formatCI(checkRuns);
  const reviewSummary = formatReviewers(pr);

  return [
    buildHeaderBlock(pr),
    buildMetadataBlock(pr),
    ...(reviewSummary 
      ? [buildReviewersBlock(pr)] 
      : []),
    buildDividerBlock(),
    buildCIBlock(checkRuns),
    buildDividerBlock(),
    ...buildSummaryBlocks(summarySections),
    {
      type: "actions",
      elements: [{
        type: "button",
        text: { type: "plain_text", text: "Open PR →", emoji: true },
        url: pr.html_url,
        style: "primary",
      }],
    },
    {
      type: "context",
      elements: [{
        type: "mrkdwn",
        text: `_Summary generated by gh-summary bot · ${new Date().toUTCString()}_`,
      }],
    },
  ];
}
